/***************************************************************
                         catherineMdl.h
                               
Catherine's model and animation data, generated as a binary file
with Arabiki64 like so:
arabiki64.exe -f sample/CatherineExported.S64 -t sample/CatherineMaterials.txt -n Catherine -o catherineMdl
***************************************************************/

// Generated by Arabiki64 V1.4
// By Buu342

// Mesh data
#define MESHCOUNT_Catherine 19

#define MESH_Catherine_Bang         0
#define MESH_Catherine_Ponytail     1
#define MESH_Catherine_Head         2
#define MESH_Catherine_Chest        3
#define MESH_Catherine_LeftArm      4
#define MESH_Catherine_RightArm     5
#define MESH_Catherine_LeftFemur    6
#define MESH_Catherine_RightFemur   7
#define MESH_Catherine_LeftFoot     8
#define MESH_Catherine_RightFoot    9
#define MESH_Catherine_LeftForearm  10
#define MESH_Catherine_LeftHand     11
#define MESH_Catherine_RightForearm 12
#define MESH_Catherine_RightHand    13
#define MESH_Catherine_LeftLeg      14
#define MESH_Catherine_RightLeg     15
#define MESH_Catherine_Pad          16
#define MESH_Catherine_Pelvis       17
#define MESH_Catherine_Sword        18

// Animation data
#define ANIMATIONCOUNT_Catherine 8

#define ANIMATION_Catherine_Attack1    0
#define ANIMATION_Catherine_Idle       1
#define ANIMATION_Catherine_Roll       2
#define ANIMATION_Catherine_Run        3
#define ANIMATION_Catherine_Sneak      4
#define ANIMATION_Catherine_ThrowKnife 5
#define ANIMATION_Catherine_Tired      6
#define ANIMATION_Catherine_Walk       7

// Texture data
#define TEXTURECOUNT_Catherine 5

#define TEXTURE_BackTex         0
#define TEXTURE_BootTex         1
#define TEXTURE_ChestTex        2
#define TEXTURE_KnifeSheatheTex 3
#define TEXTURE_PantsTex        4

// Extern definitions
extern u8 _CatherineSegmentRomStart[];
extern u8 _CatherineSegmentRomEnd[];