/***************************************************************
                         catherineTex.h
                               
This file imports the textures as sprites for DragonFS. The 
GLuint variables are important, as the names are supposed to
match the ones in Blender. Those names are used by the structures 
generated by, which expects these GLuints to be declared somewhere.
***************************************************************/

#define CATHERINE_TETXURE_COUNT 8

GLuint BackTex;
GLuint BootTex;
GLuint ChestTex;
GLuint KnifeSheatheTex;
GLuint PantsTex;
GLuint FaceTex;
GLuint FaceBlink1Tex;
GLuint FaceBlink2Tex;

static const char *catherine_texture_paths[CATHERINE_TETXURE_COUNT] = {
    "rom:/BackTex.sprite",
    "rom:/BootTex.sprite",
    "rom:/ChestTex.sprite",
    "rom:/KnifeSheatheTex.sprite",
    "rom:/PantsTex.sprite",
    "rom:/FaceTex.sprite",
    "rom:/FaceBlink1Tex.sprite",
    "rom:/FaceBlink2Tex.sprite"
};