#ifndef _SAUSN64_DLIST_H
#define _SAUSN64_DLIST_H

    typedef enum {
        DPFillRectangle = 0,
        DPScisFillRectangle,
        DPFullSync,
        DPLoadSync,
        DPTileSync,
        DPPipeSync,
        DPLoadTLUT_pal16,
        DPLoadTLUT_pal256,
        DPLoadTextureBlock,
        DPLoadTextureBlock_4b,
        DPLoadTextureTile,
        DPLoadTextureTile_4b,
        DPLoadBlock,
        DPNoOp,
        DPNoOpTag,
        DPPipelineMode,
        DPSetBlendColor,
        DPSetEnvColor,
        DPSetFillColor,
        DPSetFogColor,
        DPSetPrimColor,
        DPSetColorImage,
        DPSetDepthImage,
        DPSetTextureImage,
        DPSetHilite1Tile,
        DPSetHilite2Tile,
        DPSetAlphaCompare,
        DPSetAlphaDither,
        DPSetColorDither,
        DPSetCombineMode,
        DPSetCombineLERP,
        DPSetConvert,
        DPSetTextureConvert,
        DPSetCycleType,
        DPSetDepthSource,
        DPSetCombineKey,
        DPSetKeyGB,
        DPSetKeyR,
        DPSetPrimDepth,
        DPSetRenderMode,
        DPSetScissor,
        DPSetTextureDetail,
        DPSetTextureFilter,
        DPSetTextureLOD,
        DPSetTextureLUT,
        DPSetTexturePersp,
        DPSetTile,
        DPSetTileSize,
        SP1Triangle,
        SP2Triangles,
        SPBranchLessZ,
        SPBranchLessZrg,
        SPBranchList,
        SPClipRatio,
        SPCullDisplayList,
        SPDisplayList,
        SPEndDisplayList,
        SPFogPosition,
        SPForceMatrix,
        SPSetGeometryMode,
        SPClearGeometryMode,
        SPInsertMatrix,
        SPLine3D,
        SPLineW3D,
        SPLoadUcode,
        SPLoadUcodeL,
        SPLookAt,
        SPMatrix,
        SPModifyVertex,
        SPPerspNormalize,
        SPPopMatrix,
        SPSegment,
        SPSetLights0,
        SPSetLights1,
        SPSetLights2,
        SPSetLights3,
        SPSetLights4,
        SPSetLights5,
        SPSetLights6,
        SPSetLights7,
        SPSetStatus,
        SPNumLights,
        SPLight,
        SPLightColor,
        SPTexture,
        SPTextureRectangle,
        SPScisTextureRectangle,
        SPTextureRectangleFlip,
        SPVertex,
        SPViewport,
        SPBgRectCopy,
        SPBgRect1Cyc,
        SPObjRectangle,
        SPObjRectangleR,
        SPObjSprite,
        SPObjMatrix,
        SPObjSubMatrix,
        SPObjRenderMode,
        SPObjLoadTxtr,
        SPObjLoadTxRect,
        SPObjLoadTxRectR,
        SPObjLoadTxSprite,
        SPSelectDL,
        SPSelectBranchDL
    } DListCName;

    typedef struct {
        DListCName id;
        char* name;
        int argcount;
        int size;
    } DListCommand;

    DListCommand commands_f3dex2[] = {
        {DPFillRectangle, "DPFillRectangle", 4, 1},
        {DPScisFillRectangle, "DPScisFillRectangle", 4, 1},
        {DPFullSync, "DPFullSync", 0, 1},
        {DPLoadSync, "DPLoadSync", 0, 1},
        {DPTileSync, "DPTileSync", 0, 1},
        {DPPipeSync, "DPPipeSync", 0, 1},
        {DPLoadTLUT_pal16, "DPLoadTLUT_pal16", 2, 6},
        {DPLoadTLUT_pal256, "DPLoadTLUT_pal256", 1, 6},
        {DPLoadTextureBlock, "DPLoadTextureBlock", 12, 7},
        {DPLoadTextureBlock_4b, "DPLoadTextureBlock_4b", 11, 7},
        {DPLoadTextureTile, "DPLoadTextureTile", 16, 7},
        {DPLoadTextureTile_4b, "DPLoadTextureTile_4b", 15, 7},
        {DPLoadBlock, "DPLoadBlock", 5, 1},
        {DPNoOp, "DPNoOp", 0, 1},
        {DPNoOpTag, "DPNoOpTag", 1, 1},
        {DPPipelineMode, "DPPipelineMode", 1, 1},
        {DPSetBlendColor, "DPSetBlendColor", 4, 1},
        {DPSetEnvColor, "DPSetEnvColor", 4, 1},
        {DPSetFillColor, "DPSetFillColor", 1, 1},
        {DPSetFogColor, "DPSetFogColor", 4, 1},
        {DPSetPrimColor, "DPSetPrimColor", 6, 1},
        {DPSetColorImage, "DPSetColorImage", 4, 1},
        {DPSetDepthImage, "DPSetDepthImage", 1, 1},
        {DPSetTextureImage, "DPSetTextureImage", 4, 1},
        {DPSetHilite1Tile, "DPSetHilite1Tile", 4, 1},
        {DPSetHilite2Tile, "DPSetHilite2Tile", 4, 1},
        {DPSetAlphaCompare, "DPSetAlphaCompare", 1, 1},
        {DPSetAlphaDither, "DPSetAlphaDither", 1, 1},
        {DPSetColorDither, "DPSetColorDither", 1, 1},
        {DPSetCombineMode, "DPSetCombineMode", 2, 1},
        {DPSetCombineLERP, "DPSetCombineLERP", 16, 1},
        {DPSetConvert, "DPSetConvert", 6, 1},
        {DPSetTextureConvert, "DPSetTextureConvert", 1, 1},
        {DPSetCycleType, "DPSetCycleType", 1, 1},
        {DPSetDepthSource, "DPSetDepthSource", 1, 1},
        {DPSetCombineKey, "DPSetCombineKey", 1, 1},
        {DPSetKeyGB, "DPSetKeyGB", 6, 1},
        {DPSetKeyR, "DPSetKeyR", 3, 1},
        {DPSetPrimDepth, "DPSetPrimDepth", 2, 1},
        {DPSetRenderMode, "DPSetRenderMode", 2, 1},
        {DPSetScissor, "DPSetScissor", 5, 1},
        {DPSetTextureDetail, "DPSetTextureDetail", 1, 1},
        {DPSetTextureFilter, "DPSetTextureFilter", 1, 1},
        {DPSetTextureLOD, "DPSetTextureLOD", 1, 1},
        {DPSetTextureLUT, "DPSetTextureLUT", 1, 1},
        {DPSetTexturePersp, "DPSetTexturePersp", 1, 1},
        {DPSetTile, "DPSetTile", 12, 1},
        {DPSetTileSize, "DPSetTileSize", 5, 1},
        {SP1Triangle, "SP1Triangle", 4, 1},
        {SP2Triangles, "SP2Triangles", 8, 1},
        {SPBranchLessZ, "SPBranchLessZ", 6, 2},
        {SPBranchLessZrg, "SPBranchLessZrg", 8, 2},
        {SPBranchList, "SPBranchList", 1, 1},
        {SPClipRatio, "SPClipRatio", 1, 4},
        {SPCullDisplayList, "SPCullDisplayList", 2, 1},
        {SPDisplayList, "SPDisplayList", 1, 1},
        {SPEndDisplayList, "SPEndDisplayList", 0, 1},
        {SPFogPosition, "SPFogPosition", 2, 1},
        {SPForceMatrix, "SPForceMatrix", 1, 2},
        {SPSetGeometryMode, "SPSetGeometryMode", 1, 1},
        {SPClearGeometryMode, "SPClearGeometryMode", 1, 1},
        {SPInsertMatrix, "SPInsertMatrix", 2, 1},
        {SPLine3D, "SPLine3D", 3, 1},
        {SPLineW3D, "SPLineW3D", 4, 1},
        {SPLoadUcode, "SPLoadUcode", 2, 2},
        {SPLoadUcodeL, "SPLoadUcodeL", 1, 2},
        {SPLookAt, "SPLookAt", 1, 2},
        {SPMatrix, "SPMatrix", 2, 1},
        {SPModifyVertex, "SPModifyVertex", 3, 1},
        {SPPerspNormalize, "SPPerspNormalize", 1, 1},
        {SPPopMatrix, "SPPopMatrix", 1, 1},
        {SPSegment, "SPSegment", 2, 1},
        {SPSetLights0, "SPSetLights0", 1, 3},
        {SPSetLights1, "SPSetLights1", 1, 3},
        {SPSetLights2, "SPSetLights2", 1, 4},
        {SPSetLights3, "SPSetLights3", 1, 5},
        {SPSetLights4, "SPSetLights4", 1, 6},
        {SPSetLights5, "SPSetLights5", 1, 7},
        {SPSetLights6, "SPSetLights6", 1, 8},
        {SPSetLights7, "SPSetLights7", 1, 9},
        {SPSetStatus, "SPSetStatus", 2, 1},
        {SPNumLights, "SPNumLights", 1, 1},
        {SPLight, "SPLight", 2, 1},
        {SPLightColor, "SPLightColor", 2, 2},
        {SPTexture, "SPTexture", 5, 1},
        {SPTextureRectangle, "SPTextureRectangle", 9, 3},
        {SPScisTextureRectangle, "SPScisTextureRectangle", 9, 3},
        {SPTextureRectangleFlip, "SPTextureRectangleFlip", 9, 3},
        {SPVertex, "SPVertex", 3, 1},
        {SPViewport, "SPViewport", 1, 1},
        {SPBgRectCopy, "SPBgRectCopy", 1, 1},
        {SPBgRect1Cyc, "SPBgRect1Cyc", 1, 1},
        {SPObjRectangle, "SPObjRectangle", 1, 1},
        {SPObjRectangleR, "SPObjRectangleR", 1, 1},
        {SPObjSprite, "SPObjSprite", 1, 1},
        {SPObjMatrix, "SPObjMatrix", 1, 1},
        {SPObjSubMatrix, "SPObjSubMatrix", 1, 1},
        {SPObjRenderMode, "SPObjRenderMode", 1, 1},
        {SPObjLoadTxtr, "SPObjLoadTxtr", 1, 1},
        {SPObjLoadTxRect, "SPObjLoadTxRect", 1, 1},
        {SPObjLoadTxRectR, "SPObjLoadTxRectR", 1, 1},
        {SPObjLoadTxSprite, "SPObjLoadTxSprite", 1, 1},
        {SPSelectDL, "SPSelectDL", 4, 2},
        {SPSelectBranchDL, "SPSelectBranchDL", 4, 2},
    };

    extern void construct_dl();
    
#endif