#ifndef _SAUSN64_DLIST_H
#define _SAUSN64_DLIST_H

    #include "mesh.h"

    typedef enum {
        DPFillRectangle = 0,
        DPScisFillRectangle,
        DPFullSync,
        DPLoadSync,
        DPTileSync,
        DPPipeSync,
        DPLoadTLUT_pal16,
        DPLoadTLUT_pal256,
        DPLoadTextureBlock,
        DPLoadTextureBlock_4b,
        DPLoadTextureTile,
        DPLoadTextureTile_4b,
        DPLoadBlock,
        DPNoOp,
        DPNoOpTag,
        DPPipelineMode,
        DPSetBlendColor,
        DPSetEnvColor,
        DPSetFillColor,
        DPSetFogColor,
        DPSetPrimColor,
        DPSetColorImage,
        DPSetDepthImage,
        DPSetTextureImage,
        DPSetHilite1Tile,
        DPSetHilite2Tile,
        DPSetAlphaCompare,
        DPSetAlphaDither,
        DPSetColorDither,
        DPSetCombineMode,
        DPSetCombineLERP,
        DPSetConvert,
        DPSetTextureConvert,
        DPSetCycleType,
        DPSetDepthSource,
        DPSetCombineKey,
        DPSetKeyGB,
        DPSetKeyR,
        DPSetPrimDepth,
        DPSetRenderMode,
        DPSetScissor,
        DPSetTextureDetail,
        DPSetTextureFilter,
        DPSetTextureLOD,
        DPSetTextureLUT,
        DPSetTexturePersp,
        DPSetTile,
        DPSetTileSize,
        SP1Triangle,
        SP2Triangles,
        SPBranchLessZ,
        SPBranchLessZrg,
        SPBranchList,
        SPClipRatio,
        SPCullDisplayList,
        SPDisplayList,
        SPEndDisplayList,
        SPFogPosition,
        SPForceMatrix,
        SPSetGeometryMode,
        SPClearGeometryMode,
        SPInsertMatrix,
        SPLine3D,
        SPLineW3D,
        SPLoadUcode,
        SPLoadUcodeL,
        SPLookAt,
        SPMatrix,
        SPModifyVertex,
        SPPerspNormalize,
        SPPopMatrix,
        SPSegment,
        SPSetLights0,
        SPSetLights1,
        SPSetLights2,
        SPSetLights3,
        SPSetLights4,
        SPSetLights5,
        SPSetLights6,
        SPSetLights7,
        SPSetStatus,
        SPNumLights,
        SPLight,
        SPLightColor,
        SPTexture,
        SPTextureRectangle,
        SPScisTextureRectangle,
        SPTextureRectangleFlip,
        SPVertex,
        SPViewport,
        SPBgRectCopy,
        SPBgRect1Cyc,
        SPObjRectangle,
        SPObjRectangleR,
        SPObjSprite,
        SPObjMatrix,
        SPObjSubMatrix,
        SPObjRenderMode,
        SPObjLoadTxtr,
        SPObjLoadTxRect,
        SPObjLoadTxRectR,
        SPObjLoadTxSprite,
        SPSelectDL,
        SPSelectBranchDL
    } DListCName;

    typedef struct {
        DListCName id;
        char* name;
        int argcount;
        int size;
    } DListCommand;

    extern const DListCommand commands_f3dex2[];

    extern linkedList* dlist_frommesh(s64Mesh* mesh, char isbinary);
    extern void        construct_dl(char isbinary);
    
#endif