/***************************************************************
                           texture.c
                             
Outputs the parsed data to a file
***************************************************************/

#include <stdio.h>
#include <stdlib.h>
#include "main.h"
#include "texture.h"
#include "mesh.h"
#include "animation.h"

#define STRBUF_SIZE 512
#define RADIAN 57.2957795

/*==============================
    write_output_text
    Writes the output to a text file
==============================*/

void write_output_text()
{
    FILE* fp;
    FILE* fp_temp;
    listNode* curnode;
    int tempc;
    char strbuff[STRBUF_SIZE];
    
    // Open the file
    fp = fopen(global_outputname, "w+");
    if (fp == NULL)
        terminate("Error: Unable to open file for writing\n");
        
    // Print the header
    fprintf(fp, "// Generated by "PROGRAM_NAME" V"PROGRAM_VERSION"\n");
    fprintf(fp, "// By Buu342\n");
    
    // Iterate through all the meshes and print their names
    
    fprintf(fp, "// Mesh count: %d\n", list_meshes.size);
    for (curnode = list_meshes.head; curnode != NULL; curnode = curnode->next)
    {
        s64Mesh* mesh = (s64Mesh*)curnode->data;
        fprintf(fp, "// * gfx_%s_%s | MESH_%s_%s\n", global_modelname, mesh->name, global_modelname, mesh->name);
    }
    
    // Iterate through all the animations and print their names
    
    fprintf(fp, "// Animation count: %d\n", list_animations.size);
    for (curnode = list_animations.head; curnode != NULL; curnode = curnode->next)
    {
        s64Anim* anim = (s64Anim*)curnode->data;
        fprintf(fp, "// * anim_%s_%s | ANIMATION_%s_%s\n", global_modelname, anim->name, global_modelname, anim->name);
    }
    fputs("\n", fp);
    
    // Dump our temporary file into our final file
    sprintf(strbuff, "temp_%s", global_outputname);
    fp_temp = fopen(strbuff, "r+");
    if (fp_temp == NULL)
        terminate("Error: Unable to open temporary file for reading\n");
    while ((tempc = fgetc(fp_temp)) != EOF)
       fputc(tempc, fp);
    fclose(fp_temp);
    remove(strbuff);
    
    // Write the animation data
    fputs("\n", fp);
    fputs("/*********************************\n"
          "          Animation Data\n"
          "*********************************/", fp);
    
    for (curnode = list_animations.head; curnode != NULL; curnode = curnode->next)
    {
        listNode* keyfnode;
        s64Anim* anim = (s64Anim*)curnode->data;
        fputs("\n\n", fp);
        
        // Print an array of framedata
        for (keyfnode = anim->keyframes.head; keyfnode != NULL; keyfnode = keyfnode->next)
        {
            listNode* fdatanode;
            s64Keyframe* keyf = (s64Keyframe*)keyfnode->data;
            fprintf(fp, "FrameData anim_%s_%s_framedata%d[] = {\n", global_modelname, anim->name, keyf->keyframe);
            for (fdatanode = keyf->framedata.head; fdatanode != NULL; fdatanode = fdatanode->next)
            {
                s64FrameData* fdata = (s64FrameData*)fdatanode->data;
                fprintf(fp, "    {%.4f, %.4f, %.4f, %.4f, %.4f, %.4f, %.4f, %.4f, %.4f},\n", 
                    fdata->translation.x, fdata->translation.y, fdata->translation.z,
                    fdata->rotation.x*RADIAN, fdata->rotation.y*RADIAN, fdata->rotation.z*RADIAN,
                    fdata->scale.x, fdata->scale.y, fdata->scale.z
                );
            }
            fprintf(fp, "};\n");
        }
        
        // Then print an array of keyframes
        
        fprintf(fp, "KeyFrame anim_%s_%s_keyframes[] = {\n", global_modelname, anim->name);
        for (keyfnode = anim->keyframes.head; keyfnode != NULL; keyfnode = keyfnode->next)
        {
            s64Keyframe* keyf = (s64Keyframe*)keyfnode->data;
            fprintf(fp, "    {%d, %d, anim_%s_%s_framedata%d},\n", keyf->keyframe, list_meshes.size, global_modelname, anim->name, keyf->keyframe);
        }
        fprintf(fp, "};\n", global_modelname, anim->name);
        
        // Finally, print the animation
        fprintf(fp, "Animation anim_%s_%s[] = {\"%s\", %d, anim_%s_%s_keyframes};", global_modelname, anim->name, anim->name, anim->keyframes.size, global_modelname, anim->name);
    }
    
    // Finally, print the generated macros
    fputs("\n", fp);
    fputs("/*********************************\n"
          "              Macros\n"
          "*********************************/", fp);
    fputs("\n\n", fp);
    for (curnode = list_meshes.head; curnode != NULL; curnode = curnode->next)
    {
        s64Mesh* mesh = (s64Mesh*)curnode->data;
        fprintf(fp, "#define MESH_%s_%s gfx_%s_%s\n", global_modelname, mesh->name, global_modelname, mesh->name);
    }
    for (curnode = list_animations.head; curnode != NULL; curnode = curnode->next)
    {
        s64Anim* anim = (s64Anim*)curnode->data;
        fprintf(fp, "#define ANIMATION_%s_%s anim_%s_%s\n", global_modelname, anim->name, global_modelname, anim->name);
    }
    fputs("\n", fp);
        
    // Finish
    if (!global_quiet) printf("*Wrote output to '%s'", global_outputname);
    fclose(fp);
}


/*==============================
    write_output_binary
    NOT IMPLEMENTED!
    Writes the output to a binary file.
==============================*/

void write_output_binary()
{
    FILE* fp;
    
    // Open the file
    fp = fopen(global_outputname, "wb+");
    if (fp == NULL)
        terminate("Error: Unable to open file for writing\n");
    
    // TODO
        
    if (!global_quiet) printf("*Wrote output to '%s'", global_outputname);
    fclose(fp);
}